### ISSUE TITLE
データをソースコードから切り出す

### ISSUE THREAD

**Issue by t-morisawa** [t-morisawa/scamper#4]
https://github.com/t-morisawa/scamper/issues/2 より。

# 管理方法
 - yaml
 - markdown
 - yaml + markdown
 - json
 - DB

## yaml
yamlならこんな感じ。

```
swot:
  title: SWOT
  description: 説明
  item:
   - key: 強み
     key_en: Strength
     description: 説明
   - key: 強み
     key_en: Strength
     description: 説明
   - ...
```

### pros

全てのデータを一元管理できる。

### cons

説明を記述するには若干貧弱である。

## markdown

```
# SWOT

SWOTは意思決定のための手法です。
内部・外部要因のプラス・マイナス要因を分析し、目標が達成可能かを判断します。

目標を一つ思い浮かべて、それに対する現状分析をフォームに入力していきましょう。

## Strength 強み

[内部][プラス]どのような強みがあるか？/どのように強みを活かすか？
...
```

### pros
- 複雑なdescriptionを書くことができる

### cons
 - パーサの実装が複雑になりそう
 - 項目毎にファイル分割したりするのはかなりだるい

## yaml + markdown

yamlにマークダウンへのパスを貼り付ける。

```
swot:
  title: SWOT
  description: <markdownへのリンク>
  item:
   - key: 強み
     key_en: Strength
     description: <markdownへのリンク>
   - key: 強み
     key_en: Strength
     description: <markdownへのリンク>
   - ...
```

```
# SWOT

SWOTは意思決定のための手法です。
内部・外部要因のプラス・マイナス要因を分析し、目標が達成可能かを判断します。

目標を一つ思い浮かべて、それに対する現状分析をフォームに入力していきましょう。
```

### pros
 - 複雑なdescriptionを書くことができる
 - 一覧性が高い

### cons
 - 項目毎にファイル分割したりするのはだるい

## DB

考慮外とする。サイトの全コンテンツを静的に配信したいため。
